[package]
name = "tuio-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dyn_partial_eq = "0.1.2"
indexmap = "1.9.2"
local-ip-address = "0.5.1"
ringbuffer = "0.12.0"
rosc = "0.9.1"
